import { ArrowDown, ArrowUp, Plus, Trash2 } from "lucide-react";
import type { Proposal } from "../types/proposal";
import { blankPricingItem, blankTimelineItem, uid } from "../utils/proposal";
import { calculatePricing, formatCurrency, lineTotal } from "../utils/pricing";
import { AiAssistant } from "./ai-assistant";
import { Button, Card, Field, Select, TextArea } from "./ui";

type Props = { proposal: Proposal; onChange: (proposal: Proposal) => void };
const currencies = ["IDR", "USD", "SGD", "AUD", "EUR"] as const;

export function ProposalEditor({ proposal, onChange }: Props) {
  const set = (patch: Partial<Proposal>) => onChange({ ...proposal, ...patch });
  const summary = calculatePricing(proposal.pricing, proposal.taxRate, proposal.additionalCost);
  const moveScope = (index: number, direction: -1 | 1) => {
    const next = [...proposal.scope];
    const target = index + direction;
    if (target < 0 || target >= next.length) return;
    [next[index], next[target]] = [next[target], next[index]];
    set({ scope: next });
  };

  return <div className="grid gap-4 pb-8">
    <Card title="Informasi Proposal"><div className="grid gap-3 md:grid-cols-2"><Field label="Nomor Proposal" value={proposal.proposalNumber} onChange={(e) => set({ proposalNumber: e.target.value })} /><Field label="Tanggal" type="date" value={proposal.proposalDate} onChange={(e) => set({ proposalDate: e.target.value })} /><Field label="Masa Berlaku" type="date" value={proposal.validUntil} onChange={(e) => set({ validUntil: e.target.value })} /><Field label="Judul" value={proposal.title} onChange={(e) => set({ title: e.target.value })} /><Select label="Template" value={proposal.template} onChange={(e) => set({ template: e.target.value as Proposal["template"] })}><option value="modern">Modern</option><option value="minimal">Minimal</option><option value="corporate">Corporate</option></Select><Select label="Currency" value={proposal.currency} onChange={(e) => set({ currency: e.target.value as Proposal["currency"] })}>{currencies.map((currency) => <option key={currency}>{currency}</option>)}</Select></div></Card>
    <Card title="Informasi Perusahaan"><div className="grid gap-3 md:grid-cols-2"><Field label="Nama Perusahaan" value={proposal.company.name} onChange={(e) => set({ company: { ...proposal.company, name: e.target.value } })} /><Field label="Logo URL / Data URL" value={proposal.company.logo} onChange={(e) => set({ company: { ...proposal.company, logo: e.target.value } })} /><Field label="Email" value={proposal.company.email} onChange={(e) => set({ company: { ...proposal.company, email: e.target.value } })} /><Field label="Telepon" value={proposal.company.phone} onChange={(e) => set({ company: { ...proposal.company, phone: e.target.value } })} /><Field label="Website" value={proposal.company.website} onChange={(e) => set({ company: { ...proposal.company, website: e.target.value } })} /><TextArea label="Alamat" value={proposal.company.address} onChange={(e) => set({ company: { ...proposal.company, address: e.target.value } })} /></div></Card>
    <Card title="Informasi Klien"><div className="grid gap-3 md:grid-cols-2"><Field label="Perusahaan Klien" value={proposal.client.companyName} onChange={(e) => set({ client: { ...proposal.client, companyName: e.target.value } })} /><Field label="Nama PIC" value={proposal.client.picName} onChange={(e) => set({ client: { ...proposal.client, picName: e.target.value } })} /><Field label="Email" value={proposal.client.email} onChange={(e) => set({ client: { ...proposal.client, email: e.target.value } })} /><Field label="Telepon" value={proposal.client.phone} onChange={(e) => set({ client: { ...proposal.client, phone: e.target.value } })} /><TextArea label="Alamat" value={proposal.client.address} onChange={(e) => set({ client: { ...proposal.client, address: e.target.value } })} /></div></Card>
    <Card title="Project Overview"><div className="grid gap-3"><Field label="Nama Proyek" value={proposal.project.name} onChange={(e) => set({ project: { ...proposal.project, name: e.target.value } })} /><TextArea label="Deskripsi" value={proposal.project.description} onChange={(e) => set({ project: { ...proposal.project, description: e.target.value } })} /><TextArea label="Tujuan" value={proposal.project.objectives} onChange={(e) => set({ project: { ...proposal.project, objectives: e.target.value } })} /></div></Card>
    <Card title="Scope of Work"><div className="grid gap-2">{proposal.scope.map((item, index) => <div key={item.id} className="flex gap-2"><input className="flex-1 rounded-lg border border-slate-200 px-3 py-2" value={item.title} onChange={(e) => set({ scope: proposal.scope.map((row) => row.id === item.id ? { ...row, title: e.target.value } : row) })} /><Button variant="ghost" onClick={() => moveScope(index, -1)}><ArrowUp size={15} /></Button><Button variant="ghost" onClick={() => moveScope(index, 1)}><ArrowDown size={15} /></Button><Button variant="ghost" onClick={() => set({ scope: proposal.scope.filter((row) => row.id !== item.id) })}><Trash2 size={15} /></Button></div>)}<Button variant="secondary" onClick={() => set({ scope: [...proposal.scope, { id: uid(), title: "" }] })}><Plus size={15} />Tambah pekerjaan</Button></div></Card>
    <Card title="Deliverables"><div className="grid gap-2">{proposal.deliverables.map((item) => <div key={item.id} className="flex gap-2"><input className="flex-1 rounded-lg border border-slate-200 px-3 py-2" value={item.title} onChange={(e) => set({ deliverables: proposal.deliverables.map((row) => row.id === item.id ? { ...row, title: e.target.value } : row) })} /><Button variant="ghost" onClick={() => set({ deliverables: proposal.deliverables.filter((row) => row.id !== item.id) })}><Trash2 size={15} /></Button></div>)}<Button variant="secondary" onClick={() => set({ deliverables: [...proposal.deliverables, { id: uid(), title: "" }] })}><Plus size={15} />Tambah deliverable</Button></div></Card>
    <Card title="Timeline"><div className="grid gap-3">{proposal.timeline.map((item) => <div key={item.id} className="grid gap-2 rounded-lg bg-slate-50 p-3 dark:bg-neutral-900 md:grid-cols-2"><Field label="Tahap" value={item.phase} onChange={(e) => set({ timeline: proposal.timeline.map((row) => row.id === item.id ? { ...row, phase: e.target.value } : row) })} /><Field label="Mulai" type="date" value={item.startDate} onChange={(e) => set({ timeline: proposal.timeline.map((row) => row.id === item.id ? { ...row, startDate: e.target.value } : row) })} /><Field label="Selesai" type="date" value={item.endDate} onChange={(e) => set({ timeline: proposal.timeline.map((row) => row.id === item.id ? { ...row, endDate: e.target.value } : row) })} /><Field label="Durasi" value={item.duration} onChange={(e) => set({ timeline: proposal.timeline.map((row) => row.id === item.id ? { ...row, duration: e.target.value } : row) })} /><Button className="md:justify-self-start" variant="ghost" onClick={() => set({ timeline: proposal.timeline.filter((row) => row.id !== item.id) })}><Trash2 size={15} />Hapus</Button><TextArea label="Keterangan" className="md:col-span-2" value={item.notes} onChange={(e) => set({ timeline: proposal.timeline.map((row) => row.id === item.id ? { ...row, notes: e.target.value } : row) })} /></div>)}<Button variant="secondary" onClick={() => set({ timeline: [...proposal.timeline, blankTimelineItem()] })}><Plus size={15} />Tambah timeline</Button></div></Card>
    <Card title="Pricing"><div className="grid gap-3">{proposal.pricing.map((item) => <div key={item.id} className="grid gap-2 rounded-lg p-3 md:grid-cols-2"><input placeholder="Item" className="rounded border border-slate-200 px-2 py-2" value={item.item} onChange={(e) => set({ pricing: proposal.pricing.map((row) => row.id === item.id ? { ...row, item: e.target.value } : row) })} /><input placeholder="Description" className="rounded border border-slate-200 px-2 py-2" value={item.description} onChange={(e) => set({ pricing: proposal.pricing.map((row) => row.id === item.id ? { ...row, description: e.target.value } : row) })} /><input type="number" min="0" className="rounded border border-slate-200 px-2 py-2" value={item.quantity} onChange={(e) => set({ pricing: proposal.pricing.map((row) => row.id === item.id ? { ...row, quantity: Number(e.target.value) } : row) })} /><input className="rounded border border-slate-200 px-2 py-2" value={item.unit} onChange={(e) => set({ pricing: proposal.pricing.map((row) => row.id === item.id ? { ...row, unit: e.target.value } : row) })} /><input type="number" min="0" className="rounded border border-slate-200 px-2 py-2" value={item.price} onChange={(e) => set({ pricing: proposal.pricing.map((row) => row.id === item.id ? { ...row, price: Number(e.target.value) } : row) })} /><input type="number" min="0" className="rounded border border-slate-200 px-2 py-2" value={item.discount} onChange={(e) => set({ pricing: proposal.pricing.map((row) => row.id === item.id ? { ...row, discount: Number(e.target.value) } : row) })} /><output className="rounded bg-slate-50 px-2 py-2 text-sm font-semibold dark:bg-neutral-900">{formatCurrency(lineTotal(item), proposal.currency)}</output><Button variant="ghost" onClick={() => set({ pricing: proposal.pricing.filter((row) => row.id !== item.id) })}><Trash2 size={15} />Hapus</Button></div>)}<div className="grid gap-3 md:grid-cols-2"><Field label="Tax %" type="number" min="0" value={proposal.taxRate} onChange={(e) => set({ taxRate: Number(e.target.value) })} /><Field label="Additional Cost" type="number" min="0" value={proposal.additionalCost} onChange={(e) => set({ additionalCost: Number(e.target.value) })} /></div><Button variant="secondary" onClick={() => set({ pricing: [...proposal.pricing, blankPricingItem()] })}><Plus size={15} />Tambah item</Button><div className="rounded-lg bg-slate-100 p-3 text-sm font-semibold text-slate-950 dark:bg-neutral-900 dark:text-slate-100">Grand total: {formatCurrency(summary.grandTotal, proposal.currency)}</div></div></Card>
    <Card title="Payment Terms"><div className="grid gap-3 md:grid-cols-2"><Field label="Down Payment" value={proposal.paymentTerms.downPayment} onChange={(e) => set({ paymentTerms: { ...proposal.paymentTerms, downPayment: e.target.value } })} /><Field label="Jatuh Tempo" value={proposal.paymentTerms.dueDate} onChange={(e) => set({ paymentTerms: { ...proposal.paymentTerms, dueDate: e.target.value } })} /><Field label="Metode" value={proposal.paymentTerms.method} onChange={(e) => set({ paymentTerms: { ...proposal.paymentTerms, method: e.target.value } })} /><TextArea label="Termin Pembayaran" value={proposal.paymentTerms.schedule} onChange={(e) => set({ paymentTerms: { ...proposal.paymentTerms, schedule: e.target.value } })} /><TextArea label="Rekening" value={proposal.paymentTerms.bankInfo} onChange={(e) => set({ paymentTerms: { ...proposal.paymentTerms, bankInfo: e.target.value } })} /></div></Card>
    <Card title="Terms, Notes, Signature"><div className="grid gap-3"><TextArea label="Terms & Conditions" value={proposal.terms} onChange={(e) => set({ terms: e.target.value })} /><TextArea label="Notes" value={proposal.notes} onChange={(e) => set({ notes: e.target.value })} /><div className="grid gap-3 md:grid-cols-2"><Field label="Prepared By - Nama" value={proposal.preparedBy.name} onChange={(e) => set({ preparedBy: { ...proposal.preparedBy, name: e.target.value } })} /><Field label="Client Approval - Nama" value={proposal.clientApproval.name} onChange={(e) => set({ clientApproval: { ...proposal.clientApproval, name: e.target.value } })} /><Field label="Prepared By - Jabatan" value={proposal.preparedBy.title} onChange={(e) => set({ preparedBy: { ...proposal.preparedBy, title: e.target.value } })} /><Field label="Client Approval - Jabatan" value={proposal.clientApproval.title} onChange={(e) => set({ clientApproval: { ...proposal.clientApproval, title: e.target.value } })} /></div></div></Card>
    <AiAssistant proposal={proposal} onChange={onChange} />
  </div>;
}
